name: Pre Release (Check Tag & Dry Only Publish Pub Dev)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Setup Version
        id: setup
        run: |
          echo "TAG VERSION: $GITHUB_REF_NAME"
          echo "RELEASE VERSION: ${GITHUB_REF_NAME#v}"
          echo "::set-output name=release_name::${GITHUB_REF_NAME#v}"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.5
      - name: Check Flutter Version
        run: |
          flutter doctor -v
          flutter --version
      - name: Setup Pub Dev Credential
        run: |
          mkdir -p ~/.config/dart
          echo ${{ secrets.PUB_CREDENTIAL_JSON }} > ~/.config/dart/pub-credentials.json
          ls ~/.config/dart
          cat ~/.config/dart/pub-credentials.json
      - name: Pub Dev Dry Run
        run: |
          flutter pub publish --dry-run
          
