name: Create Release & Publish Pub Dev

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pub-dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3
      - name: Setup Version
        id: setup
        run: |
          echo "TAG VERSION: $GITHUB_REF_NAME"
          echo "RELEASE VERSION: ${GITHUB_REF_NAME#v}"
          echo "::set-output name=release_name::${GITHUB_REF_NAME#v}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ steps.setup.outputs.release_name }}
          draft: false
          prerelease: false
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.5
      - run: |
          flutter doctor -v
          flutter --version
      - name: Setup Pub Dev Credential
        run: |
          mkdir -p ~/.config/dart
          echo ${{ secrets.PUB_CREDENTIAL_JSON }} > ~/.config/dart/pub-credentials.json
          ls ~/.config/dart
          cat ~/.config/dart/pub-credentials.json
      - name: Publish To Pub Dev
        run: |
          flutter pub publish
          
